package cn.creditloans.core.entity.db;

import java.util.Date;

public class DbZqrjzhtxx {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private int id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zqrlx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zqrlx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zqrmc
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zqrmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zqrzjlx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zqrzjlx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zqrzjhm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zqrzjhm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zhtbh
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zhtbh;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.zhthm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String zhthm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.tx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String tx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.ztw
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String ztw;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.dbhtxx_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private Integer dbhtxxId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.status
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.user_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.org_code
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private String orgCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.create_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column db_zqrjzhtxx.update_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.id
	 * 
	 * @return the value of db_zqrjzhtxx.id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getZqrlx() {
		return zqrlx;
	}

	public void setZqrlx(String zqrlx) {
		this.zqrlx = zqrlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.zqrmc
	 * 
	 * @return the value of db_zqrjzhtxx.zqrmc
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZqrmc() {
		return zqrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.zqrmc
	 * 
	 * @param zqrmc
	 *            the value for db_zqrjzhtxx.zqrmc
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZqrmc(String zqrmc) {
		this.zqrmc = zqrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.zqrzjlx
	 * 
	 * @return the value of db_zqrjzhtxx.zqrzjlx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZqrzjlx() {
		return zqrzjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.zqrzjlx
	 * 
	 * @param zqrzjlx
	 *            the value for db_zqrjzhtxx.zqrzjlx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZqrzjlx(String zqrzjlx) {
		this.zqrzjlx = zqrzjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.zqrzjhm
	 * 
	 * @return the value of db_zqrjzhtxx.zqrzjhm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZqrzjhm() {
		return zqrzjhm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.zqrzjhm
	 * 
	 * @param zqrzjhm
	 *            the value for db_zqrjzhtxx.zqrzjhm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZqrzjhm(String zqrzjhm) {
		this.zqrzjhm = zqrzjhm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.zhtbh
	 * 
	 * @return the value of db_zqrjzhtxx.zhtbh
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZhtbh() {
		return zhtbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.zhtbh
	 * 
	 * @param zhtbh
	 *            the value for db_zqrjzhtxx.zhtbh
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZhtbh(String zhtbh) {
		this.zhtbh = zhtbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.zhthm
	 * 
	 * @return the value of db_zqrjzhtxx.zhthm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZhthm() {
		return zhthm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.zhthm
	 * 
	 * @param zhthm
	 *            the value for db_zqrjzhtxx.zhthm
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZhthm(String zhthm) {
		this.zhthm = zhthm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.tx
	 * 
	 * @return the value of db_zqrjzhtxx.tx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getTx() {
		return tx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.tx
	 * 
	 * @param tx
	 *            the value for db_zqrjzhtxx.tx
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setTx(String tx) {
		this.tx = tx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.ztw
	 * 
	 * @return the value of db_zqrjzhtxx.ztw
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getZtw() {
		return ztw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.ztw
	 * 
	 * @param ztw
	 *            the value for db_zqrjzhtxx.ztw
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setZtw(String ztw) {
		this.ztw = ztw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.dbhtxx_id
	 * 
	 * @return the value of db_zqrjzhtxx.dbhtxx_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public Integer getDbhtxxId() {
		return dbhtxxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.dbhtxx_id
	 * 
	 * @param dbhtxxId
	 *            the value for db_zqrjzhtxx.dbhtxx_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setDbhtxxId(Integer dbhtxxId) {
		this.dbhtxxId = dbhtxxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.status
	 * 
	 * @return the value of db_zqrjzhtxx.status
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.status
	 * 
	 * @param status
	 *            the value for db_zqrjzhtxx.status
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.user_id
	 * 
	 * @return the value of db_zqrjzhtxx.user_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.user_id
	 * 
	 * @param userId
	 *            the value for db_zqrjzhtxx.user_id
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.org_code
	 * 
	 * @return the value of db_zqrjzhtxx.org_code
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.org_code
	 * 
	 * @param orgCode
	 *            the value for db_zqrjzhtxx.org_code
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.create_time
	 * 
	 * @return the value of db_zqrjzhtxx.create_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.create_time
	 * 
	 * @param createTime
	 *            the value for db_zqrjzhtxx.create_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column db_zqrjzhtxx.update_time
	 * 
	 * @return the value of db_zqrjzhtxx.update_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column db_zqrjzhtxx.update_time
	 * 
	 * @param updateTime
	 *            the value for db_zqrjzhtxx.update_time
	 * 
	 * @mbggenerated Tue May 26 13:10:42 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}