package cn.creditloans.core.entity.db;

import java.util.Date;

public class DbBdbrxx {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.id
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private int id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.bdbrlx
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String bdbrlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.bdbrmc
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String bdbrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.bdbrzjlx
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String bdbrzjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.bdbrzjhm
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String bdbrzjhm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.ztw
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String ztw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.dbhtxx_id
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private int dbhtxxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.status
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private int status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.user_id
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private int userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.org_code
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.create_time
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_bdbrxx.update_time
	 * @mbggenerated  Mon May 25 15:13:50 CST 2015
	 */
	private Date updateTime;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getBdbrlx() {
		return bdbrlx;
	}
	public void setBdbrlx(String bdbrlx) {
		this.bdbrlx = bdbrlx;
	}
	public String getBdbrmc() {
		return bdbrmc;
	}
	public void setBdbrmc(String bdbrmc) {
		this.bdbrmc = bdbrmc;
	}
	public String getBdbrzjlx() {
		return bdbrzjlx;
	}
	public void setBdbrzjlx(String bdbrzjlx) {
		this.bdbrzjlx = bdbrzjlx;
	}
	public String getBdbrzjhm() {
		return bdbrzjhm;
	}
	public void setBdbrzjhm(String bdbrzjhm) {
		this.bdbrzjhm = bdbrzjhm;
	}
	public String getZtw() {
		return ztw;
	}
	public void setZtw(String ztw) {
		this.ztw = ztw;
	}
	public int getDbhtxxId() {
		return dbhtxxId;
	}
	public void setDbhtxxId(int dbhtxxId) {
		this.dbhtxxId = dbhtxxId;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getOrgCode() {
		return orgCode;
	}
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
}