package cn.creditloans.core.entity.db;

import java.math.BigDecimal;
import java.util.Date;

public class DbDcmxxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.dcrq
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private String dcrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.dcje
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private BigDecimal dcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private Integer dbhtxxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.status
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.user_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.org_code
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.create_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_dcmxxx.update_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    private Date updateTime;

    
    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.dcrq
     *
     * @return the value of db_dcmxxx.dcrq
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public String getDcrq() {
        return dcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.dcrq
     *
     * @param dcrq the value for db_dcmxxx.dcrq
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setDcrq(String dcrq) {
        this.dcrq = dcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.dcje
     *
     * @return the value of db_dcmxxx.dcje
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public BigDecimal getDcje() {
        return dcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.dcje
     *
     * @param dcje the value for db_dcmxxx.dcje
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setDcje(BigDecimal dcje) {
        this.dcje = dcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.dbhtxx_id
     *
     * @return the value of db_dcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public Integer getDbhtxxId() {
        return dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.dbhtxx_id
     *
     * @param dbhtxxId the value for db_dcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setDbhtxxId(Integer dbhtxxId) {
        this.dbhtxxId = dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.status
     *
     * @return the value of db_dcmxxx.status
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.status
     *
     * @param status the value for db_dcmxxx.status
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.user_id
     *
     * @return the value of db_dcmxxx.user_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.user_id
     *
     * @param userId the value for db_dcmxxx.user_id
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.org_code
     *
     * @return the value of db_dcmxxx.org_code
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.org_code
     *
     * @param orgCode the value for db_dcmxxx.org_code
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.create_time
     *
     * @return the value of db_dcmxxx.create_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.create_time
     *
     * @param createTime the value for db_dcmxxx.create_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_dcmxxx.update_time
     *
     * @return the value of db_dcmxxx.update_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_dcmxxx.update_time
     *
     * @param updateTime the value for db_dcmxxx.update_time
     *
     * @mbggenerated Wed May 27 13:34:35 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}