package cn.creditloans.core.entity.db;

import java.math.BigDecimal;
import java.util.Date;

public class DbZcmxxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.zcrq
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private String zcrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.zcje
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private BigDecimal zcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private Integer dbhtxxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.status
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.user_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.org_code
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.create_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_zcmxxx.update_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    private Date updateTime;

    

    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.zcrq
     *
     * @return the value of db_zcmxxx.zcrq
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public String getZcrq() {
        return zcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.zcrq
     *
     * @param zcrq the value for db_zcmxxx.zcrq
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setZcrq(String zcrq) {
        this.zcrq = zcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.zcje
     *
     * @return the value of db_zcmxxx.zcje
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public BigDecimal getZcje() {
        return zcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.zcje
     *
     * @param zcje the value for db_zcmxxx.zcje
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setZcje(BigDecimal zcje) {
        this.zcje = zcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.dbhtxx_id
     *
     * @return the value of db_zcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public Integer getDbhtxxId() {
        return dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.dbhtxx_id
     *
     * @param dbhtxxId the value for db_zcmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setDbhtxxId(Integer dbhtxxId) {
        this.dbhtxxId = dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.status
     *
     * @return the value of db_zcmxxx.status
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.status
     *
     * @param status the value for db_zcmxxx.status
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.user_id
     *
     * @return the value of db_zcmxxx.user_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.user_id
     *
     * @param userId the value for db_zcmxxx.user_id
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.org_code
     *
     * @return the value of db_zcmxxx.org_code
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.org_code
     *
     * @param orgCode the value for db_zcmxxx.org_code
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.create_time
     *
     * @return the value of db_zcmxxx.create_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.create_time
     *
     * @param createTime the value for db_zcmxxx.create_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_zcmxxx.update_time
     *
     * @return the value of db_zcmxxx.update_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_zcmxxx.update_time
     *
     * @param updateTime the value for db_zcmxxx.update_time
     *
     * @mbggenerated Wed May 27 15:51:16 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}