package cn.creditloans.core.dto.db;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DbBfjnmxxxDTO implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1952011700484524588L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.yjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private String yjrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.yjje
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private BigDecimal yjje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.sjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private String sjrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.qjje
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private BigDecimal qjje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.bqbfjnzt
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private String bqbfjnzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private Integer dbhtxxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.status
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.user_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.org_code
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.create_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_bfjnmxxx.update_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    private Date updateTime;

    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.yjrq
     *
     * @return the value of db_bfjnmxxx.yjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public String getYjrq() {
        return yjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.yjrq
     *
     * @param yjrq the value for db_bfjnmxxx.yjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setYjrq(String yjrq) {
        this.yjrq = yjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.yjje
     *
     * @return the value of db_bfjnmxxx.yjje
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public BigDecimal getYjje() {
        return yjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.yjje
     *
     * @param yjje the value for db_bfjnmxxx.yjje
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setYjje(BigDecimal yjje) {
        this.yjje = yjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.sjrq
     *
     * @return the value of db_bfjnmxxx.sjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public String getSjrq() {
        return sjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.sjrq
     *
     * @param sjrq the value for db_bfjnmxxx.sjrq
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setSjrq(String sjrq) {
        this.sjrq = sjrq;
    }

    public BigDecimal getQjje() {
		return qjje;
	}

	public void setQjje(BigDecimal qjje) {
		this.qjje = qjje;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.bqbfjnzt
     *
     * @return the value of db_bfjnmxxx.bqbfjnzt
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public String getBqbfjnzt() {
        return bqbfjnzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.bqbfjnzt
     *
     * @param bqbfjnzt the value for db_bfjnmxxx.bqbfjnzt
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setBqbfjnzt(String bqbfjnzt) {
        this.bqbfjnzt = bqbfjnzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.dbhtxx_id
     *
     * @return the value of db_bfjnmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public Integer getDbhtxxId() {
        return dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.dbhtxx_id
     *
     * @param dbhtxxId the value for db_bfjnmxxx.dbhtxx_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setDbhtxxId(Integer dbhtxxId) {
        this.dbhtxxId = dbhtxxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.status
     *
     * @return the value of db_bfjnmxxx.status
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.status
     *
     * @param status the value for db_bfjnmxxx.status
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.user_id
     *
     * @return the value of db_bfjnmxxx.user_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.user_id
     *
     * @param userId the value for db_bfjnmxxx.user_id
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.org_code
     *
     * @return the value of db_bfjnmxxx.org_code
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.org_code
     *
     * @param orgCode the value for db_bfjnmxxx.org_code
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.create_time
     *
     * @return the value of db_bfjnmxxx.create_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.create_time
     *
     * @param createTime the value for db_bfjnmxxx.create_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_bfjnmxxx.update_time
     *
     * @return the value of db_bfjnmxxx.update_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_bfjnmxxx.update_time
     *
     * @param updateTime the value for db_bfjnmxxx.update_time
     *
     * @mbggenerated Wed May 27 17:26:34 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}